services:
  - type: web
    name: 双选会报名系统
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: "9000"
      - key: WSGI_SERVER
        value: waitress
